travis:
  secure:
    BINSTAR_TOKEN: rb7bRmiRtK7xxXY4vw2xhSxSgdh0eD1hxF77W5r2cCWog6UVLEE5s1d812kOyvnk6sBuU8pAjUNC1McjOwX3HIXc++aj7YYcAoRJdZCwTffApG8LERsvW8tejN7NIj/XH0cjZ4T0SLCPjmwr+0Q76LNnIoalTayn5ZugEwkA3hQfDnHFyC0SNP7a/vhyNpPEhm/ReZIxYrmaz3pvPXU2rdTCKw99z8sEIhUx7IqTunW8eyaGuxiXTc0QCyZGdVgzCiTQpE/vtZEsRkq/tQC50rWyT5ol3qmjZVtnIyfPCA6Vmfy2CK9au7nyD4JhiW4EOmLlvjVcLgtfBibu+W30sMEM5oLoQ3ePFA5tl9fAGE3bDICnYBrz66fTLIds9FVJcZqYu5p9QGP/8xGmbcSGl0rlrusZ4n8q3QaC43NCwlQYPLwH+O2QLc0u3PRDPtd1y2wILu30R5x/rbCSwyB5hpNtCmOiZ7biF+1LlUVaNaP44xiBlLrK0/OxOH5z2Nawc90+hj++tziYL7ewaQUvvdjnYklVE7Y3QAjZE+xvPX0vDiHXuQi0ff6sfLlzgud37lndmGccAVtZBt6gjIRJfVWbTw9h3Es4kbTLP9UDyuMp7mO7qnkfImGFCrI8gWb6l21zGS1AZ16weTdJ9kt24TmmctF8cfn+tRmKju6H1is=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
