travis:
  secure:
    BINSTAR_TOKEN: JncUgvda7EslnC2JGsaHMA7uyqiFKt/WoIB3LVJ4hhQ3vZdCOHMsbRdiQu4odEy0vrs1txlfZ5e8OTvXuLFupGV3rW1s4OkoLK2FiGPPzDvkib+xxNXYGxe2ei+o+gkSp/u+qdlCScgiH+S0LP9UZkPspfpk20+v3vRU7D+BinjMMS/hU4yvt5rUlWASvfmNZdkfQQ3x3EdHLVdLOo/gYsLWa0DiMvBIeWdBx5nmxcJEYV+EEz7rxTZ95Y/7PFmbIkQXW0ipGExra6ivUCMRbph3Wd8ZuYND9glwjcbb2Bd3C37HPy46+e3vFq0SJzvlBjUjcR1sjJ3V9gc7F2l6tsC0QmOEaZTb/GF9p/N0Pf3yii4nD7iuVLzPOMe442Pl8Gg0Cx7uNyjJqWc+oFeUrYRPgmSaSbgWu2EfkTg1BhL4vVUNxfkBZQbTjvIjw6eyZD7zoonYCtZ1Hwl5DqBuTgl+kXuxZtHPwuEwfv/8ueJ9cEgNmh30OZCGkKvRC/Yc8TpnqaT/SqLpXRwrhrabzhrDQRYJcJep85kr3GWZ3gYSHpJdSnYDS/rky3L7K2SUaQpNsEl2xuSBWz1WykjiN3R6t6XrJZPq0V84y6olEeVxsB4fo7JmTnphrW5oeDy43l8rpn6PMkGtkcIBgcAqMjgCQidSCwqeqz33efT7lOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
